---
- name: configure the nanopi to run tests on a schedule
  gather_facts: false
  vars_files:
    - vars.yml
  hosts: nanopis
  #  handlers:
  #
  #    - name: shutdown nanopi
  #      become: true
  #      shell: sleep 3 && shutdown now
  #      async: 1
  #      poll: 0
  #      ignore_errors: true

  tasks:

    - name: ensure apt packages are present
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - iperf3
        - python3
        - python3-pip
        - python3-dev
        - python3-setuptools
          
    - name: ensure pip3 packages are present
      become: true
      pip:
        name: "{{ item }}"
        state: latest
        executable: pip3
      loop:
        - pip
        - setuptools
        - wheel
        - requests
        - iperf3
        - apscheduler
        - maya

    - name: generate random number between 0 and 59, which is when intense tests will run
      script: files/generate_minute.py
      register: test_time

    - name: copy schedule.py into place
      copy:
        src: files/schedule.py
        dest: /home/nanopi/schedule.py
        mode: 0700

    - name: copy scheduled-testing.service to systemd directory
      become: true
      template:
        src: scheduled-testing.service
        dest: /etc/systemd/system/scheduled-testing.service

    - name: enable and start scheduled-testing.service
      become: true
      systemd:
        name: scheduled-testing
        enabled: true
        state: restarted
        daemon_reload: true
  #      notify:
  #        - shutdown nanopi
